(()=>{'use strict';const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const colors=['#729dc4','#9bbec5','#d0ccab','#dab987','#cd9b92'];let period=5;
function render(payload,c){const box=document.querySelector('#peRiver');if(!box||code!==c)return;const model=payload.model||W01PEModel.build(payload.rows||[],payload.prices||[]),all=model.rows,m=model.multiples;if(!all.length||!m.length){box.innerHTML='<h3>本益比河流</h3><p>本益比估值不適用／無可靠價格與正值 PE 同日資料。</p>';return}
const end=all.at(-1).date,start=new Date(end+'T00:00:00Z');start.setUTCFullYear(start.getUTCFullYear()-period);const rows=all.filter(r=>r.date>=start.toISOString().slice(0,10)),vals=rows.filter(r=>r.pe>0).map(r=>r.pe),last=rows.at(-1),high=Math.max(...rows.flatMap(r=>[r.price,...(r.bands||[])]))*1.05,low=Math.max(0,Math.min(...rows.flatMap(r=>[r.price,...(r.bands||[])]))*.94),y=v=>252-(v-low)/(high-low||1)*211,x=i=>58+i/(rows.length-1||1)*402;
const segments=[];let segment=[];rows.forEach((r,i)=>{if(r.bands){segment.push({r,i})}else if(segment.length){segments.push(segment);segment=[]}});if(segment.length)segments.push(segment);
const bands=colors.map((color,j)=>segments.map(s=>'<polygon fill="'+color+'" opacity=".23" points="'+[...s.map(({r,i})=>x(i)+','+y(r.bands[j+1])),...s.slice().reverse().map(({r,i})=>x(i)+','+y(r.bands[j]))].join(' ')+'"/>').join('')).join('');
box.dataset.pePeriod=period;box.dataset.peRows=rows.length;box.dataset.peAxis='PRICE_TWD';box.dataset.peMultiples=JSON.stringify(m);
box.innerHTML='<h3>本益比河流 · 價格估值帶</h3><div>'+[3,5].map(n=>'<button data-pe-range="'+n+'" class="'+(period===n?'active':'')+'">'+n+'年</button>').join('')+'</div><p>實際價格 '+last.price.toFixed(2)+' 元 · '+last.date+'<br>歷史 PE '+(last.pe?last.pe.toFixed(2)+'x':'N/A')+' · EPS 參考代理 '+(last.eps?last.eps.toFixed(2):'N/A')+'</p><svg class="pe-chart" viewBox="0 0 520 300" role="img" aria-label="股價與 EPS 乘固定本益比價格帶，共用元價格軸">'+bands+[0,1,2,3,4].map(i=>{const v=low+(high-low)*i/4;return '<line x1="58" x2="460" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#57718a" opacity=".3"/><text x="53" y="'+(y(v)+4)+'" text-anchor="end" fill="#a5b9cc" font-size="11">'+v.toFixed(0)+'</text>'}).join('')+m.map((v,j)=>segments.map(s=>'<polyline data-band="'+v+'" fill="none" stroke="'+(colors[Math.min(j,4)])+'" opacity=".65" stroke-width=".8" points="'+s.map(({r,i})=>x(i)+','+y(r.bands[j])).join(' ')+'"/>').join('')).join('')+'<polyline class="actual-price-line" fill="none" stroke="#83e2d5" stroke-width="2" points="'+rows.map((r,i)=>x(i)+','+y(r.price)).join(' ')+'"/><text x="58" y="24" fill="#a5b9cc" font-size="12">元（TWD）</text><text x="58" y="280" fill="#a5b9cc" font-size="11">'+rows[0].date+'</text><text x="385" y="280" fill="#a5b9cc" font-size="11">'+end+'</text><rect class="pe-hover-area" x="58" y="41" width="402" height="211" fill="transparent"/></svg><div class="pe-tooltip" role="status">移到圖中查看同日價格、EPS 參考值與估值帶</div><p class="pe-legend">'+m.map((v,i)=>'<span style="color:'+colors[Math.min(i,4)]+'">'+v.toFixed(1)+'x（P'+model.quantiles[i]+'）</span>').join(' · ')+'<br><span style="color:#83e2d5">━━ 實際股價</span></p><small>倍數取完整可用 5 年 PE 分布 P10/25/40/60/75/90，3Y/5Y 使用同組固定倍數。PriceBand = EPS_t × M。EPS_t 為同日收盤／交易所歷史 PE 的參考 EPS 代理，受 PE 四捨五入影響，不等同逐季公布 EPS 的獨立重建。非正值／缺值日不畫估值帶，不補值。<br>Historical valuation research view；部分歷史 EPS publication timing 尚未完全 PIT-certified。資料修訂 vintage 未獨立認證，不可直接用於 backtest；未使用年度預估 EPS。歷史估值區間不是 intrinsic value。<br>可用期間 '+all[0].date+'～'+end+'；'+rows.length+' 個價格日，'+rows.filter(r=>!r.bands).length+' 日 PE 不適用／缺值。<a href="'+E(payload.source)+'" target="_blank" rel="noopener">PE 來源</a> · <a href="'+E(payload.price_source||'https://finmind.github.io/tutor/TaiwanMarket/Technical/')+'" target="_blank" rel="noopener">股價來源</a></small>';
const hover=box.querySelector('.pe-hover-area'),chart=box.querySelector('svg');hover.onpointermove=e=>{const b=chart.getBoundingClientRect(),px=(e.clientX-b.left)/b.width*520,i=Math.max(0,Math.min(rows.length-1,Math.round((px-58)/402*(rows.length-1)))),r=rows[i],j=r.pe===null?-1:m.findIndex(v=>r.pe<v),band=r.pe===null?'N/A':j===0?'低於 '+m[0]+'x':j<0?'高於 '+m.at(-1)+'x':m[j-1]+'～'+m[j]+'x',p=r.pe===null?null:vals.filter(v=>v<=r.pe).length/vals.length*100;box.querySelector('.pe-tooltip').textContent=r.date+'｜股價 '+r.price.toFixed(2)+' 元｜TTM EPS 參考代理 '+(r.eps?r.eps.toFixed(3):'N/A')+'｜歷史 PE '+(r.pe?r.pe.toFixed(2)+'x':'N/A')+'｜'+band+'｜'+period+'Y 百分位 '+(p!==null?p.toFixed(1)+'%':'N/A');};
box.querySelectorAll('[data-pe-range]').forEach(b=>b.onclick=()=>{period=+b.dataset.peRange;render(payload,c)})}
async function load(c){period=5;const el=document.querySelector('#peRiver');if(/^00\d/.test(c)){el.innerHTML='<h3>本益比河流</h3><p>此商品不適用個股本益比河流圖。</p>';return}el.innerHTML='<h3>本益比河流</h3><p>按需取得價格估值帶…</p>';try{let r=await fetch('/ui-data/pe-river-'+encodeURIComponent(c)+'.json');if(!r.ok)r=await fetch('/api/valuation?code='+encodeURIComponent(c));if(!r.ok)throw Error('Unavailable');const p=await r.json();if(code===c)render(p,c)}catch{if(code===c)el.innerHTML='<h3>本益比河流</h3><p>N/A：歷史價格／估值來源暫不可用，不以預估 EPS 補造。</p>'}}
window.W01PERiver={load,render};})();
