(()=>{'use strict';
const VIEW_URL='/w01-approved-research-view.json';let promise;
const load=()=>promise||(promise=fetch(VIEW_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Research View ${r.status}`);return r.json()}).then(v=>{if(v.contract_id!=='W01_APPROVED_RESEARCH_VIEW'||v.canonical_count!==2971||v.evidence_count!==3295)throw new Error('Research View identity mismatch');return v}));
const eventId=row=>String(row?.[18]?.event_id||''),ticker=row=>String(row?.[1]||'').match(/\b(00\d{3}[A-Z]?|\d{4})\b/)?.[1]||'',action=row=>String(row?.[8]||'');
async function recordFor(row){const view=await load(),id=eventId(row),code=ticker(row),act=action(row);return view.records.find(x=>x.event_id===id&&x.ticker===code&&x.signal===act)||view.records.find(x=>x.event_id===id)||null}
async function applyToWebsite(){const view=await load(),byId=new Map(view.records.map(x=>[x.event_id,x]));let matched=0;for(const row of data){const approved=byId.get(eventId(row));if(!approved)continue;row[7]=approved.recommendation_reason;row[8]=approved.signal;row[10]=approved.execution_status;const meta=row[18]||{};row[18]={...meta,display_reason:approved.recommendation_reason,reason_summary:approved.recommendation_reason,canonical_action:approved.semantics?.action??meta.canonical_action,approved_research_view:true};matched++}if(matched!==view.canonical_count)throw new Error(`Website Research View match mismatch: ${matched}/${view.canonical_count}`);populateSignalFilter();populateStatusFilter();render();return matched}
const value=x=>x??'';
function addRows(sheet,headers,rows){sheet.addRow(headers);rows.forEach(r=>sheet.addRow(r));sheet.getRow(1).font={bold:true};sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:headers.length}}}
function outcomeRows(store){return Array.isArray(store)?store:(store.outcomes||store.records||[])}
async function buildWorkbook(){if(!window.ExcelJS)throw new Error('XLSX 元件尚未載入');const [view,store]=await Promise.all([load(),fetch('/outcome-store.json').then(r=>{if(!r.ok)throw new Error(`Outcome Store ${r.status}`);return r.json()})]);const workbook=new ExcelJS.Workbook();workbook.creator='W01 APPROVED RESEARCH VIEW';workbook.created=new Date();
const signals=workbook.addWorksheet('Signals');addRows(signals,['Signal Ref','Event ID','訊號日','股號','股票','老師','訊號','執行狀態','推薦原因','建議／進場價','目標','停損','配置／部位','操作 Context','出場範圍'],view.records.map(x=>[x.signal_ref,x.event_id,x.signal_date,x.ticker,x.stock_name,x.teacher,x.signal,x.execution_status,x.recommendation_reason,value(x.semantics?.price),value(x.semantics?.target),value(x.semantics?.stop),value(x.semantics?.allocation),value(x.semantics?.context),value(x.semantics?.exit_scope)]));
const evidence=workbook.addWorksheet('Evidence');addRows(evidence,['Signal Ref','Evidence ID','Event ID','來源','老師','股號','Observed At','Source Reference','Evidence Grade','Precision / Component','Batch / Source Event','Raw Text','Raw Evidence'],view.records.flatMap(x=>x.evidence.map(e=>[x.signal_ref,e.evidence_id,e.event_id,e.source,e.teacher,e.ticker,e.observed_at,e.source_reference,e.lineage?.evidence_grade,e.lineage?.component_id,e.lineage?.source_event_id,e.raw_text,e.raw_evidence])));
const info=workbook.addWorksheet('Export_Info');addRows(info,['欄位','值'],[['Contract',view.contract_id],['Contract version',view.contract_version],['Website role','Primary Research Workspace'],['XLSX role','Offline Mirror'],['Access layer','Soft Gate Only'],['Soft gate warning','1028 is friction, not a security boundary'],['Canonical',view.canonical_count],['Evidence',view.evidence_count],['Outcome',view.outcome_count],['READY',view.ready_count],['Teacher Registry',view.teacher_registry_count],['Outcome Blockers',view.outcome_blockers?.length||0],['Generated At',new Date().toISOString()]]);
const outcomes=workbook.addWorksheet('Outcomes'),allOutcomes=outcomeRows(store),outcomeHeaders=[...new Set(allOutcomes.flatMap(Object.keys))];addRows(outcomes,outcomeHeaders,allOutcomes.map(o=>outcomeHeaders.map(k=>typeof o[k]==='object'?JSON.stringify(o[k]):value(o[k]))));
if(view.outcome_blockers?.length){const blockers=workbook.addWorksheet('Outcome_Blockers'),headers=[...new Set(view.outcome_blockers.flatMap(Object.keys))];addRows(blockers,headers,view.outcome_blockers.map(o=>headers.map(k=>typeof o[k]==='object'?JSON.stringify(o[k]):value(o[k]))))}return {workbook,view,outcomeCount:allOutcomes.length}}
async function download(codeOverride){const code=codeOverride??prompt('輸入 XLSX 下載碼（soft gate，非安全邊界）'),status=document.querySelector('#xlsxStatus');if(code===null)return false;if(String(code)!=='1028'){if(status)status.textContent='下載碼錯誤，未建立 XLSX';return false}const button=document.querySelector('#xlsxButton');button?.classList.add('loading');if(button)button.disabled=true;if(status)status.textContent='正在從 W01_APPROVED_RESEARCH_VIEW 建立 XLSX…';try{const {workbook,view,outcomeCount}=await buildWorkbook(),buffer=await workbook.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),link=document.createElement('a'),stamp=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}).replaceAll('-','').slice(4);link.href=url;link.download=`W01_Research_Offline_Mirror_${stamp}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(status)status.textContent=`XLSX 已建立：${view.canonical_count} Signals / ${view.evidence_count} Evidence / ${outcomeCount} Outcomes`;return true}finally{button?.classList.remove('loading');if(button)button.disabled=false}}
window.w01ApprovedResearch={load,recordFor,applyToWebsite,buildWorkbook,download};window.downloadXlsx=()=>download();const button=document.querySelector('#xlsxButton');if(button)button.onclick=()=>download();applyToWebsite().catch(error=>{const status=document.querySelector('#xlsxStatus');if(status)status.textContent='Research View 載入失敗：'+error.message;console.error(error)});})();
