(()=>{'use strict';const key='W01ChartPreferencesV1',E=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
const nav=document.createElement('nav');nav.className='ux-nav';nav.innerHTML='<strong>W01</strong><a href="/">← 研究工作台</a><span>v1.13 LOCAL CANDIDATE</span>';document.body.prepend(nav);
function prefs(){const p=read();document.querySelector('#chartPreferences').innerHTML='<h3>圖表偏好 <span class="ux-muted">僅本機保存</span></h3><div class="chart-pref">'+[5,10,20,60,180,240].map(n=>'<label><input type="checkbox" data-sma-show="'+n+'" '+(p.hidden?.[n]?'':'checked')+'> SMA '+n+' <select data-sma-bold="'+n+'"><option value="0">一般</option><option value="1" '+(p.bold?.[n]?'selected':'')+'>加粗</option></select></label>').join('')+'<button id="resetChart">還原預設</button></div>';
document.querySelector('#chartPreferences').onchange=ev=>{const t=ev.target,p=read();if(t.dataset.smaShow){p.hidden||={};p.hidden[t.dataset.smaShow]=!t.checked}if(t.dataset.smaBold){p.bold||={};p.bold[t.dataset.smaBold]=t.value==='1'}localStorage.setItem(key,JSON.stringify(p));if(studyData){drawKline(studyData.candles||[]);setRangeButtons()}};
document.querySelector('#resetChart').onclick=()=>{localStorage.removeItem(key);currentRange='2m';prefs();setRangeButtons();loadStudy(code,false)};}
async function brief(){const c=code,etf=/^00\d{2,3}[A-Z]?$/.test(c);let d={events:[],outcomes:[]};try{const r=await fetch('/ui-data/stocks/'+encodeURIComponent(c)+'.json');if(r.ok)d=await r.json()}catch{}if(code!==c)return;const es=d.events||[],recent=es.filter(e=>e.date).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);const unknown=es.filter(e=>!e.date).length;const review=es.filter(e=>e.meta?.review_status==='REVIEW_REQUIRED').length;
document.querySelector('#stockBrief').innerHTML='<div class="ux-grid"><article class="ux-card"><span class="ux-label">Decision Brief</span><h3>'+E(d.name||c)+'｜'+(etf?'ETF 研究介面':'個股研究')+'</h3><p>'+es.length+' 個既有訊號；'+new Set(es.map(e=>e.teacher)).size+' 位老師。最新動作：'+E(recent[0]?.status||'尚無本工作訊號')+'</p><p class="ux-muted">描述既有資訊，不提供綜合分數或買賣指令。</p></article><article class="ux-card"><span class="ux-label">Why Now</span><p>'+E(recent[0]?.reason||'無可確認的近期推薦原因。')+'</p><p class="ux-muted">原因來自既有 Evidence；不把歷史持有敘述當成當日買進。</p></article></div><h3>操作 Timeline → Evidence</h3><div class="ux-timeline">'+recent.map((e,i)=>'<button data-event="'+i+'">'+E(e.date)+' '+E(e.teacher)+'<br>'+E(e.status)+'｜'+E(e.price)+'</button>').join('')+'</div><div id="stockEvidence"></div>';
document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const e=recent[+b.dataset.event];document.querySelector('#stockEvidence').innerHTML='<h3>Source → Raw Evidence</h3><p>'+E(e.reason)+'</p><pre class="ux-raw">'+E(JSON.stringify(e.meta?.evidence_records||e.meta?.raw_evidence||e.reason,null,2))+'</pre>'});
if(etf){const kind=c==='00631L'?'槓桿 ETF':c.endsWith('R')?'反向 ETF（倍率未確認）':'ETF（類型未確認）';document.querySelector('#fundamentals').innerHTML='<article class="ux-card"><h3>Instrument Adapter｜'+kind+'</h3><p>股票 EPS / 月營收：不適用。<a href="https://www.yuantaetfs.com/product/detail/00631L/Basic_information" target="_blank">00631L 官方產品資料</a>。'+(c==='00631L'?'元大台灣50正2；單日正向2倍型，長期報酬不等於標的累積報酬2倍。':'標的／槓桿倍率／費用／折溢價：UNKNOWN。')+'</p><p class="ux-muted">上市櫃 ETF 介面可開啟；不以股票基本面硬套 ETF。</p></article>';return;}
document.querySelector('#fundamentals').innerHTML='<article class="ux-card">月營收與實際 EPS：按需載入中…</article>';try{const f=await fetch('/api/fundamentals?code='+c).then(r=>r.json());if(code!==c)return;const rs=f.revenue||[],max=Math.max(1,...rs.map(x=>x.value));let lines='';for(const [year,color]of [[2024,'#8299c0'],[2025,'#e4b065'],[2026,'#6ee2c5']]){const a=rs.filter(x=>x.year===year).sort((a,b)=>a.month-b.month);lines+='<polyline fill="none" stroke="'+color+'" stroke-width="2" points="'+a.map(x=>(45+(x.month-1)*65)+','+(220-x.value/max*175)).join(' ')+'"/>';lines+=a.filter(x=>year===2026&&x.yoy!==null).map(x=>'<text x="'+(45+(x.month-1)*65)+'" y="'+(208-x.value/max*175)+'" fill="'+color+'" font-size="11" text-anchor="middle">'+(x.yoy>=0?'+':'')+x.yoy.toFixed(1)+'%</text>').join('');lines+=a.map(x=>'<circle class="revenue-dot" cx="'+(45+(x.month-1)*65)+'" cy="'+(220-x.value/max*175)+'" r="4" fill="'+color+'"><title>'+year+'/'+x.month+'｜'+x.value.toFixed(2)+' 億元｜YoY '+(x.yoy===null?'N/A':x.yoy.toFixed(2)+'%')+'</title></circle>').join('')}
document.querySelector('#fundamentals').innerHTML='<article class="ux-card"><h3>月營收｜三年同月比較 <span class="ux-muted">億元</span></h3><p><span style="color:#8299c0">● 2024</span>　<span style="color:#e4b065">● 2025</span>　<span style="color:#6ee2c5">● 2026（僅已發布月份）</span></p>'+(rs.length?'<svg class="revenue-chart" viewBox="0 0 800 260">'+lines+Array.from({length:12},(_,i)=>'<text x="'+(45+i*65)+'" y="250" fill="#9ab1c4" font-size="12">'+(i+1)+'月</text>').join('')+'</svg>':'<p>來源暫無可讀資料；不補零、不推估未發布月份。</p>')+'<h3>EPS</h3><p>2025A：'+E(f.eps2025??'N/A')+'｜2026E：N/A｜2027E：N/A</p><p class="ux-muted">預估 EPS 缺少可靠來源，維持 N/A。來源：<a href="https://finmind.github.io/tutor/TaiwanMarket/Fundamental/" target="_blank">FinMind 官方資料文件</a>｜取得時間 '+E(f.updated_at)+'｜'+E(f.gap||'取得時間不等同來源發布日。')+'</p></article>'}catch(e){document.querySelector('#fundamentals').innerHTML='<article class="ux-card">基本面來源不可用｜EPS / 月營收 N/A</article>'}}
const original=loadStudy;loadStudy=async(...args)=>{const pending=original(...args);brief();await pending;};prefs();brief();})();
