(()=>{'use strict';const key='W01ChipOrderV1',ids=['foreign','trust','margin','marginRate'];const right=document.querySelector('.right');let cards=ids.map(id=>document.querySelector('#'+id).closest('.panel'));cards.forEach((c,i)=>{c.dataset.chip=ids[i];const h=c.querySelector('h2'),handle=document.createElement('span');handle.textContent='⋮⋮';handle.draggable=true;handle.style.cursor='grab';handle.title='拖曳調整順序';h.prepend(handle);handle.ondragstart=e=>e.dataTransfer.setData('text/plain',c.dataset.chip);c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();const a=cards.find(x=>x.dataset.chip===e.dataTransfer.getData('text/plain'));if(a&&a!==c){right.insertBefore(a,c);save()}};for(const [label,delta]of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.textContent=label;b.title='移動籌碼卡片';b.onclick=()=>{const all=[...right.querySelectorAll('[data-chip]')],n=all.indexOf(c),target=all[n+delta];if(target){right.insertBefore(delta<0?c:target,delta<0?target:c);save()}};h.append(b)}});
function save(){localStorage.setItem(key,JSON.stringify([...right.querySelectorAll('[data-chip]')].map(x=>x.dataset.chip)))}
cards.forEach(c=>{const h=c.querySelector('h2 span');h.draggable=false;h.dataset.dragHandle='true';h.style.touchAction='none';let origin=null;h.addEventListener('pointerdown',e=>{if(e.button!==0)return;origin={x:e.clientX,y:e.clientY};h.setPointerCapture(e.pointerId);e.preventDefault()});h.addEventListener('pointerup',e=>{if(origin&&Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>6){const target=document.elementsFromPoint(e.clientX,e.clientY).map(x=>x.closest('[data-chip]')).find(Boolean);if(target&&target!==c){right.insertBefore(c,target);save()}}if(h.hasPointerCapture(e.pointerId))h.releasePointerCapture(e.pointerId);origin=null});h.addEventListener('pointercancel',()=>{origin=null})});
try{const order=JSON.parse(localStorage.getItem(key)||'[]');[...order,...ids.filter(id=>!order.includes(id))].forEach(id=>{const c=cards.find(x=>x.dataset.chip===id);if(c)right.append(c)})}catch{}const reset=document.createElement('button');reset.textContent='恢復預設順序';reset.onclick=()=>{ids.forEach(id=>right.append(cards.find(x=>x.dataset.chip===id)));localStorage.removeItem(key)};right.prepend(reset);
const original=drawKline;drawKline=function(...args){original(...args);const chart=document.querySelector('#kline'),data=args[0]||[];if(!data.length)return;const rawLow=Math.min(...data.map(r=>Number(r.low))),rawHigh=Math.max(...data.map(r=>Number(r.high))),padding=Math.max((rawHigh-rawLow)*.08,rawHigh*.01),low=rawLow-padding,high=rawHigh+padding;const bins=Array(18).fill(0),size=(rawHigh-rawLow)/18||1;data.forEach(r=>{const i=Math.min(17,Math.max(0,Math.floor(((+r.high + +r.low + +r.close)/3-rawLow)/size)));bins[i]+=Math.max(0,+r.volume||0)});const max=Math.max(1,...bins);const y=p=>42+(high-p)/(high-low)*203;bins.forEach((v,i)=>{const width=v/max*110;chart.insertBefore(svg('rect',{x:128-width,y:y(rawLow+(i+1)*size),width,height:Math.max(1,size/(high-low)*203-.5),fill:'#b0cddd',opacity:.35,'data-volume-profile':i}),chart.firstChild)});document.querySelector('#profileNote').textContent='單一成交量分布代理：每日總量分配至典型價 (高+低+收)/3；不是逐筆逐價成交，也不是實際帳戶成本。';
let start=null,moved=false;const g=svg('g',{'pointer-events':'none','data-measurement':'true'});chart.append(g);const point=e=>{const p=chart.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const t=p.matrixTransform(chart.getScreenCTM().inverse());return {x:Math.min(718,Math.max(128,t.x)),y:Math.min(245,Math.max(42,t.y))}};const price=p=>high-(p.y-42)/203*(high-low);
function draw(end){g.replaceChildren();const a=price(start),b=price(end),pct=(b/a-1)*100,bx=Math.min(end.x,490),by=Math.max(42,end.y-45);g.append(svg('rect',{x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),width:Math.abs(start.x-end.x),height:Math.abs(start.y-end.y),fill:'#70c8ff',opacity:.16}),svg('line',{x1:start.x,y1:start.y,x2:end.x,y2:end.y,stroke:pct>=0?'#6ee2c5':'#ff8eae','stroke-width':2}),svg('circle',{cx:start.x,cy:start.y,r:3,fill:'#70c8ff'}),svg('circle',{cx:end.x,cy:end.y,r:3,fill:'#70c8ff'}),svg('rect',{x:bx,y:by,width:225,height:43,rx:5,fill:'#12364c'}),svg('text',{x:bx+6,y:by+16,fill:'#fff','font-size':12},a.toFixed(2)+' → '+b.toFixed(2)),svg('text',{x:bx+6,y:by+33,fill:'#fff','font-size':12},'Δ '+(b-a>=0?'+':'')+(b-a).toFixed(2)+' | '+(pct>=0?'+':'')+pct.toFixed(2)+'%'));g.dataset.startPrice=a;g.dataset.endPrice=b;g.dataset.percent=pct;g.dataset.difference=b-a;}
chart.addEventListener('pointerdown',e=>{if(e.button!==0)return;const p=point(e);if(p.y>=245)return;start=p;moved=false;chart.setPointerCapture(e.pointerId)});chart.addEventListener('pointermove',e=>{if(!start||!chart.hasPointerCapture(e.pointerId))return;const p=point(e);if(Math.hypot(p.x-start.x,p.y-start.y)>3){moved=true;draw(p)}});chart.addEventListener('pointerup',e=>{if(start&&moved)draw(point(e));if(chart.hasPointerCapture(e.pointerId))chart.releasePointerCapture(e.pointerId);start=null});chart.style.touchAction='pan-x';};
if(studyData)drawKline(studyData.candles||[],studyData.institutions||[],studyData.holdings||[]);
})();
