(()=>{'use strict';
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.w01FilterMatch=r=>{const p=new URLSearchParams(location.search);return (!p.get('teacher')||r[18]?.teacher_id===p.get('teacher'))&&(!p.get('code')||codeOf(r[1])===p.get('code'))};
function state(){const p=new URLSearchParams(location.search),labels=[p.get('teacher'),p.get('code')].filter(Boolean);document.querySelector('#researchFilter').textContent=labels.length?'研究篩選：'+labels.join(' × ')+'（清除）':'';render()}
window.w01Link=(teacher,ticker,label)=>'<a href="?'+new URLSearchParams(Object.fromEntries([['teacher',teacher],['code',ticker]].filter(x=>x[1]))).toString()+'#stocks" data-w01-filter>'+E(label)+'</a>';
const chip=document.createElement('button');chip.id='researchFilter';document.querySelector('#q').after(chip);chip.onclick=()=>{history.pushState({},'',location.pathname+'#stocks');state()};
document.addEventListener('click',ev=>{const a=ev.target.closest('[data-w01-filter]');if(!a)return;ev.preventDefault();history.pushState({},'',a.href);quickFilter={type:'',value:'',label:''};document.querySelector('#q').value='';chooseAll(document.querySelector('#signal'));chooseAll(document.querySelector('#status'));updateQuickFilterStatus();state();document.querySelector('#stocks').scrollIntoView({behavior:'smooth'})});window.addEventListener('popstate',state);state();
const sectors=[['PCB',/PCB|載板|銅箔|玻纖/],['AI／伺服器',/AI|人工智慧|伺服器|CSP/],['半導體',/半導體|晶圓|封測|記憶體|矽光子/],['被動元件',/被動元件|電容|電阻/],['光電／面板',/面板|光電|LED/]];
let activeTeacher='';document.addEventListener('click',e=>{const b=e.target.closest('[data-teacher-drawer]');if(b)activeTeacher=b.dataset.teacherDrawer});new MutationObserver(()=>{const drawer=document.querySelector('.ux-drawer');if(!drawer||!activeTeacher||drawer.querySelector('[data-sector-detail]'))return;const p=distribution(activeTeacher),box=document.createElement('section');box.dataset.sectorDetail='true';box.innerHTML='<h3>完整標的分布</h3><p>'+E(p.rows.join(' / ')||'無可分類標的')+'</p><small>分母 '+p.n+' 個不同股票，沿用正式近三月日期篩選；依原因明示題材分類，含產業未分類，不是資金配置。舊資料日期口徑不代表本輪重新認證年份。</small>';drawer.querySelector('h2').after(box)}).observe(document.body,{childList:true});
function teacherRows(id){return data.filter(r=>r[18]?.teacher_id===id&&!partialDate(r)&&rowTime(r)>=Date.parse(window.w01Cutoff+'T00:00:00Z'))}
function distribution(id){const rs=teacherRows(id);const stocks=new Map();rs.forEach(r=>{const c=codeOf(r[1]);if(c)stocks.set(c,(stocks.get(c)||'')+' '+r[7])});const counts={};stocks.forEach(reason=>{const s=sectors.find(x=>x[1].test(reason))?.[0]||'產業未分類';counts[s]=(counts[s]||0)+1});return {n:stocks.size,rows:Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([s,n])=>s+' '+Math.round(n/stocks.size*100)+'%')}}
function style(c){const total=Object.values(c).reduce((a,b)=>a+b,0);if(!total)return '日期已明樣本不足';const n=total,b=(c.BUY+c.ADD)/n,s=(c.SELL+c.REDUCE)/n,h=c.HOLD/n;return c.SHORT&&b?'多空並用':c.SHORT/n>=.5?'偏放空':h>=.5?'偏續抱':s>=.45?'頻繁調節':c.ADD/n>=.3?'加碼布局':b>=.65?'積極布局':'布局／調節並行'}
fetch('/ui-data/index.json').then(r=>r.json()).then(d=>{window.w01Cutoff=d.cutoff;d.teachers.forEach(t=>{const rs=teacherRows(t.id);t.total=rs.length;t.count={BUY:0,ADD:0,HOLD:0,REDUCE:0,SELL:0,SHORT:0};rs.forEach(r=>{let a=r[18]?.canonical_action;if(a==='SELL'&&r[18]?.exit_scope==='PARTIAL')a='REDUCE';if(a in t.count)t.count[a]++});const r=rs.sort((a,b)=>rowTime(b)-rowTime(a))[0];t.latest=r?{date: r[18]?.resolved_date||r[18]?.signal_date||r[0],name:r[1],ticker:codeOf(r[1]),signal:r[8]}:null});document.querySelector('h1').textContent='股市同學會';const slogan=document.createElement('p');slogan.className='ux-muted';slogan.textContent='10 秒看懂市場、30 秒看懂老師、1 分鐘看懂個股';document.querySelector('h1').after(slogan);
const dates=[...new Set(data.map(r=>r[18]?.resolved_date||r[18]?.signal_date).filter(Boolean))].sort().reverse();const latest=dates[0],previous=dates[1],rs=data.filter(r=>(r[18]?.resolved_date||r[18]?.signal_date)===latest),prior=data.filter(r=>(r[18]?.resolved_date||r[18]?.signal_date)===previous);const groups=[['買／加碼',['BUY','ADD']],['賣／出場',['SELL','REDUCE']],['放空',['SHORT']]];const act=r=>r[18]?.canonical_action;const count=(a,g)=>a.filter(r=>g.includes(act(r))).length;
const recent=data.filter(r=>{const day=r[18]?.resolved_date||r[18]?.signal_date;return day&&day>=dates[4]&&r[18]?.teacher_id&&r[18].teacher_id!=='W01-T-UNKNOWN'});const topics=[['AI／半導體',/AI|人工智慧|半導體|晶圓/],['關稅政策',/關稅/],['利率／Fed',/殖利率|降息|Fed|聯準會/],['匯率',/匯率|美元|台幣/],['地緣風險',/戰爭|地緣|伊朗/]];const common=topics.map(([name,re])=>({name,rows:recent.filter(r=>re.test(r[7]))})).map(t=>({...t,teachers:new Set(t.rows.map(r=>r[18]?.teacher_id).filter(Boolean))})).filter(t=>t.teachers.size>=2).sort((a,b)=>b.teachers.size-a.teachers.size).slice(0,5);
const targets=new Map();rs.filter(r=>['BUY','ADD'].includes(act(r))).forEach(r=>{const c=codeOf(r[1]);if(!c)return;if(!targets.has(c))targets.set(c,{name:r[1],teachers:new Set()});targets.get(c).teachers.add(r[18]?.teacher_id)});
document.querySelector('#marketBrief').innerHTML='<div class="ux-grid"><article class="ux-card"><h3>市場重點</h3><small>最近五個有正式日期的來源日｜AI 描述性整理</small>'+common.map(t=>'<details><summary>'+E(t.name)+' · '+t.teachers.size+' 位老師提及</summary><p>觀察：來源反覆提及此主題；關注原因與個股影響見下列原話。未由交易筆數推定台股方向。</p>'+t.rows.slice(0,3).map(r=>'<p>'+E(r[6])+ '：'+E(r[7])+'</p>').join('')+'</details>').join('')+(common.length?'':'<p>目前沒有可確認的多老師共同題材。</p>')+'</article><article class="ux-card"><h3>來源日操作變化</h3><small>'+previous+' → '+latest+'｜相同單日 canonical 分母</small>'+groups.map(([name,g])=>{const a=count(prior,g),b=count(rs,g);return '<p><b>'+name+'</b> '+a+' → '+b+' 訊（'+(b-a>=0?'+':'')+(b-a)+'）</p>'}).join('')+'<small>續抱不歸入方向；筆數不是支持率。</small></article><article class="ux-card"><h3>布局標的</h3>'+[...targets].sort((a,b)=>b[1].teachers.size-a[1].teachers.size).slice(0,6).map(([c,t])=>'<p>'+w01Link('',c,t.name)+' · '+t.teachers.size+' 師</p>').join('')+'</article></div>';
document.querySelector('#teacherOverview').innerHTML='<table class="ux-table"><thead><tr><th>老師</th><th>3月訊號</th><th>操作風格</th><th>配置摘要 · 標的分布</th><th>n（READY）</th><th>最新操作</th></tr></thead><tbody>'+d.teachers.filter(t=>t.total||t.coverage.eligible_ready_outcomes).sort((a,b)=>a.name.localeCompare(b.name,'zh-TW')).map(t=>{const p=distribution(t.id),total=Object.values(t.count).reduce((a,b)=>a+b,0)||1;return '<tr><td><button data-teacher-drawer="'+E(t.id)+'">'+E(t.name)+'</button></td><td>'+w01Link(t.id,'',t.total)+'</td><td title="'+E(Object.entries(t.count).map(([k,v])=>k+' '+Math.round(v/total*100)+'%').join(' / '))+'">'+style(t.count)+'</td><td title="'+E('分母：日期已明近三月 '+p.n+' 個不同股票；以推薦原因明示題材分組，非持倉權重。'+p.rows.join(' / '))+'">'+E(p.rows.slice(0,3).join(' / ')||'無可分類標的')+'</td><td>'+E(t.coverage.eligible_ready_outcomes||0)+'</td><td>'+w01Link(t.id,t.latest?.ticker||String(t.latest?.name||'').match(/^\d+/)?.[0],(t.latest?.date||'')+' '+(t.latest?.name||'')+' '+(t.latest?.signal||''))+'</td></tr>'}).join('')+'</tbody></table>';
common.forEach((topic,i)=>{const details=document.querySelectorAll('#marketBrief details')[i];const text=topic.rows.map(r=>r[7]).join(' '),terms=['AI PC','先進封裝','晶圓代工','半導體','人工智慧','關稅','殖利率','降息','匯率','地緣'].filter(k=>text.includes(k)).slice(0,3);const p=document.createElement('p');p.className='ux-muted';p.textContent='觀察：'+(terms.join('、')||topic.name)+'反覆出現在推薦原因。關注點：老師把題材與個股操作連結。可能影響：相關族群關注度與波動；不足以判定大盤方向（AI 綜合觀察）。';details.before(p);details.querySelectorAll('p').forEach((p,j)=>{if(j>0){const r=topic.rows[j-1];p.append('｜來源日期 '+(r[18]?.resolved_date||r[18]?.signal_date||'UNKNOWN'))}})});
});
})();
